// data.js

// JSON de sucursales, eliminando duplicados
const sucursales = [
    'Batres Tactic',
    'Batres Carcha',
    'Farmacia Batres Central Coban',
    'Batres Coban',
    'Batres III Coban',
    'Batres Fray Bartolome',
    'Batres Teleman',
    'Batres La Tinta',
    'Farmacia Batres San Cristobal Verapaz',
    'Batres Plaza del Parque Coban',
    'Batres Chisec I',
    'Batres Don Artur Coban',
    'Batres Salama',
    'Farmacia Batres II Salama',
    'Farmacia Batres Rabinal',
    'Batres Cubulco',
    'Farmacia Batres Guastatoya',
    'Batres Guastatoya II',
    'Batres Sanarate',
    'Farmacia Batres Playa Grande',
    'Farmacia Batres Gualan',
    'Batres Zacapa',
    'Farmacia Batres Teculutan',
    'Batres Manantiales Carcha',
    'Farmacia Batres Roosevelt',
    'Farmacia Batres Vista Hermosa',
    'Farmacia Batres Calzada San Juan',
    'Farmacia Batres San Miguel Petapa',
    'Farmacia Batres San Cristobal',
    'Farmacia Batres Zona 1',
    'Farmacia Batres Zona 6',
    'Farmacia Batres Don Arthur',
    'Farmacia Batres Calle Marti',
    'Farmacia Batres BB',
    'Farmacia Batres Zona 14 H. Las Americas',
    'Farmacia Batres Escala Caes',
    'Batres Plaza Decorisima',
    'Batres BB II',
    'Batres Llano Largo Zona 25',
    'Farmacia Batres El Pulte',
    'Farmacia Batres CC Vistas de Fraijanes',
    'Farmacia Batres Monjas Jalapa',
    'Farmacia Batres Monjas Jalapa II',
    'Batres Jalapa',
    'Farmacia Batres Jalapa III',
    'Farmacia Batres Jalapa (II)',
    'Batres Manantiales Jalapa',
    'Batres Don Artur Jalapa',
    'Batres Los Manantiales Chimaltenango',
    'Batres BB Chimaltenango',
    'Batres Tecpan',
    'Batres Sinai',
    'Batres San Martin',
    'Farmacia Batres Chimaltenango',
    'Farmacia Batres San Juan Comalapa',
    'Farmacia Batres Zaragoza',
    'Batres Don Artur Chimaltenango',
    'Batres Don Artur Chimaltenango II',
    'Batres Tiquisate',
    'Batres Nueva Concepcion',
    'Farmacia Batres Villa Nueva',
    'Farmacia Batres Amatitlan',
    'Batres Retalhuleu',
    'Farmacia Batres La Trinidad Retalhuleu',
    'Batres Champerico',
    'Farmacia Batres CM XII',
    'Farmacia Batres Jutiapa',
    'Farmacia Batres Progreso Jutiapa',
    'Farmacia Batres IV Jutiapa',
    'Batres Agua Blanca Jutiapa',
    'Batres II Progreso Jutiapa',
    'Farmacia Batres Ciudad Pedro de Alvarado',
    'Farmacia Batres Moyuta',
    'Farmacia Batres Jalpatagua',
    'Farmacia Batres Cuilapa',
    'Farmacia Batres Barberena',
    'Batres Chiquimulilla',
    'Farmacia Batres II Barberena',
    'Batres Barberena III',
    'Farmacia Batres Nueva Santa Rosa',
    'Batres Manantiales Progreso Jutiapa',
    'Batres Chichicastenango',
    'Batres II Chichicastenango',
    'Farmacia Batres Central Quiché',
    'DROGUERIA CBSA',
    'Farmacia Batres Don Paco',
    'Batres Las Margaritas',
    'Batres Quiche I',
    'Batres Pachalum',
    'Batres Chichicastenango III',
    'Batres Joyabaj',
    'Farmacia Batres Joyabaj II',
    'Batres Nebaj',
    'Farmacia Batres Sacapulas',
    'Batres Don Carbari',
    'Farmacia Los Manantiales Solola',
    'Batres Panajachel',
    'Batres Santiago Atitlan',
    'Farmacia Batres Solola II',
    'Batres II Totonicapan',
    'Batres Totonicapan I',
    'Batres Momostenango',
    'Farmacia Batres San Francisco El Alto',
    'Batres Nahuala',
    'Batres Gumarkaah',
    'Batres Manantiales Quiche',
    'Farmacia Batres III Santa Lucia',
    'Farmacia Batres La Gomera',
    'Farmacia Batres II Escuintla',
    'Batres Escuintla',
    'Farmacia Batres Santa Lucia',
    'Farmacia Batres Puerto De San Jose',
    'Farmacia Batres Escuintla III',
    'Farmacia Batres Puerto San Jose II',
    'Farmacia Batres Mixco',
    'Farmacia Batres San Juan Sacatepequez',
    'Batres Don Artur Escuintla I',
    'Batres BB Escuintla I',
    'Batres Clínica Médica X',
    'Clinica Médica VII'
  ];
  
  // JSON de departamentos, eliminando duplicados
const departamentos = [
    'Alta Verapaz',
    'Baja Verapaz',
    'El Progreso',
    'Quiché',
    'Zacapa',
    'Guatemala',
    'Jalapa',
    'Chimaltenango',
    'Escuintla',
    'Retalhuleu',
    'Sacatepéquez',
    'Suchitepéquez',
    'Quetzaltenango',
    'San Marcos',
    'Huehuetenango',
    'Chiquimula',
    'Izabal',
    'Petén',
    'Jutiapa',
    'Santa Rosa',
    'Sololá',
    'Totonicapán'
  ];

  export {sucursales,departamentos}